const videoLinks = [
  {
    title: 'content creator',
    id: 1,
    posterImg: '',
    englishVideo:
      'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4',
    spanish: 'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'content creator',
    id: 2,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'animation',
    id: 3,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'https://www.youtube.com/watch?v=8Ch7dqMpNlI',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'Documentaries',
    id: 4,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'tutorials',
    id: 5,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'entertainment',
    id: 6,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'coorporate videos',
    id: 7,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'news',
    id: 8,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
];

export default videoLinks;
