const videoLinks = [
  {
    title: 'content creator',
    id: 1,
    posterImg:
      'https://uploads-ssl.webflow.com/64a1953c1a72bd5a81a24f3d/64b2dd8d4c059eab34058ca3_videocover-min.webp',
    englishVideo: 'http://twitter.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'content creator',
    id: 2,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'animation',
    id: 3,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'Documentaries',
    id: 4,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'tutorials',
    id: 5,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'entertainment',
    id: 6,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'coorporate videos',
    id: 7,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
  {
    title: 'news',
    id: 8,
    posterImg: 'https://unsplash.com/s/photos/img',
    englishVideo: 'http://google.com',
    spanish: 'http://google.com',
    spanishLatin: 'http://google.com',
    marathi: 'http://google.com',
    german: 'http://google.com',
    hindi: 'http://google.com',
    cantonese: 'http://google.com',
  },
];

export default videoLinks;
