const videoLinks = [
  {
    language: 'english',
    id: 1 as number,
    posterImg: '',
    contentcreator1:
      'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4' as string,
    contentcreator2:
      'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4' as string,
    animation:
      'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4' as string,
    documentaries:
      'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4' as string,
    tutorials: 'http://google.com' as string,
    entertainment: 'http://google.com' as string,
    coorporateVideos: 'http://google.com' as string,
    news: 'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4' as string,
  },
  {
    language: 'Spanish(port)' as string,
    id: 2 as number,
    posterImg: 'https://unsplash.com/s/photos/img' as string,
    contentcreator1: 'http://google.com' as string,
    contentcreator2: 'http://google.com' as string,
    animation: 'http://google.com' as string,
    documentaries: 'http://google.com' as string,
    tutorials: 'http://google.com' as string,
    entertainment: 'http://google.com' as string,
    coorporateVideos: 'http://google.com' as string,
    news: 'https://dl.dropboxusercontent.com/s/6ozrrrfnti2fmty/Input%20website%20videos.mp4' as string,
  },
  {
    language: 'spanish(latin)' as string,
    id: 3 as number,
    posterImg: 'https://unsplash.com/s/photos/img' as string,
    contentcreator1: 'http://google.com' as string,
    contentcreator2: 'http://google.com' as string,
    animation: 'http://google.com' as string,
    documentaries: 'http://google.com' as string,
    tutorials: 'http://google.com' as string,
    entertainment: 'http://google.com' as string,
    coorporateVideos: 'http://google.com' as string,
    news: 'http://google.com' as string,
  },
  {
    language: 'marathi' as string,
    id: 4 as number,
    posterImg: 'https://unsplash.com/s/photos/img' as string,
    contentcreator1: 'http://google.com' as string,
    contentcreator2: 'http://google.com' as string,
    animation: 'http://google.com' as string,
    documentaries: 'http://google.com' as string,
    tutorials: 'http://google.com' as string,
    entertainment: 'http://google.com' as string,
    coorporateVideos: 'http://google.com' as string,
    news: 'http://google.com' as string,
  },
  {
    language: 'german',
    id: 5 as number,
    posterImg: 'https://unsplash.com/s/photos/img' as string,
    contentcreator1: 'http://google.com' as string,
    contentcreator2: 'http://google.com' as string,
    animation: 'http://google.com' as string,
    documentaries: 'http://google.com' as string,
    tutorials: 'http://google.com' as string,
    entertainment: 'http://google.com' as string,
    coorporateVideos: 'http://google.com' as string,
    news: 'http://google.com' as string,
  },
  {
    language: 'hindi' as string,
    id: 6 as number,
    posterImg: 'https://unsplash.com/s/photos/img' as string,
    contentcreator1: 'http://google.com' as string,
    contentcreator2: 'http://google.com' as string,
    animation: 'http://google.com' as string,
    documentaries: 'http://google.com' as string,
    tutorials: 'http://google.com' as string,
    entertainment: 'http://google.com' as string,
    coorporateVideos: 'http://google.com' as string,
    news: 'http://google.com',
  },
  {
    language: 'cantonese' as string,
    id: 7 as number,
    posterImg: 'https://unsplash.com/s/photos/img' as string,
    contentcreator1: 'http://google.com' as string,
    contentcreator2: 'http://google.com' as string,
    animation: 'http://google.com' as string,
    documentaries: 'http://google.com' as string,
    tutorials: 'http://google.com' as string,
    entertainment: 'http://google.com' as string,
    coorporateVideos: 'http://google.com' as string,
    news: 'http://google.com',
  },
];

export default videoLinks;
